site_name: yaml_notes
site_url: https://chaitu-ycr.github.io/yaml_notes/
site_description: this project stores yaml notes
site_author: chaitu-ycr

repo_name: chaitu-ycr/yaml_notes
repo_url: https://github.com/chaitu-ycr/yaml_notes.git
edit_uri: blob/main/docs/

nav:
  - index.md
  - scalars.ipynb
  - sequences.ipynb
  - mappings.ipynb
  - syntax_and_structure.ipynb
  - miscellaneous.ipynb

plugins:
  - mkdocs-jupyter:
      include_requirejs: true
  - include-markdown:
      recursive: true
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search
