site_name: yaml_notes
site_url: https://chaitu-ycr.github.io/yaml_notes/
site_description: this project stores yaml notes
site_author: chaitu-ycr

repo_name: chaitu-ycr/yaml_notes
repo_url: https://github.com/chaitu-ycr/yaml_notes.git
edit_uri: blob/main/docs/

theme:
  name: readthedocs
  features:
    - toc.integrate

nav:
  - Overview: index.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
          setup_commands:
            - import sys
            - sys.path.append('./yaml_notes')
          selection:
            new_path_syntax: true
  - include-markdown:
      recursive: true
